import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module.js';
import { configureApp } from '../src/app.setup.js';
import { PrismaService } from '../src/common/database/prisma.service.js';
import { createSession, destroySession, type TestSession } from './helpers/auth.js';

describe('Módulo de protocolos (e2e)', () => {
  let app: INestApplication; let prisma: PrismaService; let session: TestSession;
  let clientId=''; let procedureId=''; let appointmentId=''; let protocolId='';
  const token=Math.random().toString(36).slice(2,8);
  beforeAll(async()=>{const module=await Test.createTestingModule({imports:[AppModule]}).compile();app=module.createNestApplication();configureApp(app);await app.init();prisma=app.get(PrismaService);session=await createSession(app,'protocols');const c=await prisma.client.create({data:{fullName:`Cliente Protocolo ${token}`}});clientId=c.id;const p=await prisma.procedure.create({data:{name:`Procedimento Protocolo ${token}`}});procedureId=p.id;await prisma.procedurePrice.create({data:{procedureId,valueCents:10000,validFrom:new Date('2026-01-01')}});const a=await prisma.appointment.create({data:{clientId,procedureId,procedureName:p.name,scheduledAt:new Date('2026-09-12T12:00:00Z'),status:'REALIZADO'}});appointmentId=a.id;});
  afterAll(async()=>{if(protocolId)await prisma.protocolSession.deleteMany({where:{protocolId}});if(protocolId)await prisma.protocol.delete({where:{id:protocolId}});await prisma.appointment.delete({where:{id:appointmentId}});await prisma.procedurePrice.deleteMany({where:{procedureId}});await prisma.procedure.delete({where:{id:procedureId}});await prisma.client.delete({where:{id:clientId}});await destroySession(app,session);await app.close();});
  it('abre ficha com snapshots e lista com filtros',async()=>{const r=await request(app.getHttpServer()).post('/api/protocols').set('Cookie',session.cookie).send({clientId,procedureId,date:'2026-09-13',title:`Protocolo ${token}`,chiefComplaint:'Queixa clínica'}).expect(201);protocolId=r.body.id;expect(r.body).toMatchObject({clientName:`Cliente Protocolo ${token}`,procedureName:`Procedimento Protocolo ${token}`,status:'EM_ANDAMENTO'});const list=await request(app.getHttpServer()).get('/api/protocols').query({search:token,status:'EM_ANDAMENTO',active:'true'}).set('Cookie',session.cookie).expect(200);expect(list.body.items).toHaveLength(1);});
  it('acrescenta sessão e mantém histórico cronológico',async()=>{await request(app.getHttpServer()).post(`/api/protocols/${protocolId}/sessions`).set('Cookie',session.cookie).send({date:'2026-09-13',procedureId,appointmentId,procedurePerformed:'Aplicação facial',evolution:'Resposta adequada'}).expect(201);await request(app.getHttpServer()).post(`/api/protocols/${protocolId}/sessions`).set('Cookie',session.cookie).send({date:'2026-09-10',procedurePerformed:'Avaliação inicial'}).expect(201);const detail=await request(app.getHttpServer()).get(`/api/protocols/${protocolId}`).set('Cookie',session.cookie).expect(200);expect(detail.body.sessions.map((x:{procedurePerformed:string})=>x.procedurePerformed)).toEqual(['Avaliação inicial','Aplicação facial']);await request(app.getHttpServer()).post(`/api/protocols/${protocolId}/sessions`).set('Cookie',session.cookie).send({date:'2026-09-14',appointmentId,procedurePerformed:'Duplicado'}).expect(409);});
  it('conclui ficha e bloqueia edição e novas sessões',async()=>{await request(app.getHttpServer()).patch(`/api/protocols/${protocolId}/status`).set('Cookie',session.cookie).send({status:'CONCLUIDO'}).expect(200);await request(app.getHttpServer()).patch(`/api/protocols/${protocolId}`).set('Cookie',session.cookie).send({title:'Alteração indevida'}).expect(409);await request(app.getHttpServer()).post(`/api/protocols/${protocolId}/sessions`).set('Cookie',session.cookie).send({date:'2026-09-15',procedurePerformed:'Indevido'}).expect(409);});
  it('protege autenticação e valida payload',async()=>{await request(app.getHttpServer()).get('/api/protocols').expect(401);await request(app.getHttpServer()).post('/api/protocols').set('Cookie',session.cookie).send({clientId:'inválido'}).expect(400);});
});
