import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { ProtocolStatus } from '../../../generated/prisma/client.js';
import { ClientQueryService } from '../../clients/services/client-query.service.js';
import { ProcedureQueryService } from '../../procedures/services/procedure-query.service.js';
import { AppointmentQueryService } from '../../appointments/services/appointment-query.service.js';
import type { CreateProtocolDto } from '../dto/create-protocol.dto.js';import type { UpdateProtocolDto } from '../dto/update-protocol.dto.js';import type { CreateProtocolSessionDto } from '../dto/create-protocol-session.dto.js';import { ProtocolRepository } from '../repositories/protocol.repository.js';
const text=(value:string|undefined)=>value===undefined?undefined:value.trim()||null;
@Injectable()
export class ProtocolService {
 constructor(private readonly protocols:ProtocolRepository,private readonly clients:ClientQueryService,private readonly procedures:ProcedureQueryService,private readonly appointments:AppointmentQueryService){}
 async create(dto:CreateProtocolDto){const client=await this.clients.getById(dto.clientId);if(!client.active)throw new BadRequestException('Cliente inativo não pode ter novo protocolo.');const procedure=dto.procedureId?await this.procedures.getById(dto.procedureId):null;if(procedure&&!procedure.active)throw new BadRequestException('Procedimento inativo não pode iniciar protocolo.');return this.protocols.create({clientId:dto.clientId,clientName:client.fullName,procedureId:dto.procedureId,procedureName:procedure?.name,date:new Date(dto.date),title:dto.title.trim(),chiefComplaint:text(dto.chiefComplaint),evaluation:text(dto.evaluation),objective:text(dto.objective),proposedProtocol:text(dto.proposedProtocol),guidelines:text(dto.guidelines),notes:text(dto.notes)});}
 async update(id:string,dto:UpdateProtocolDto){const current=await this.require(id);if(!current.active||current.status!=='EM_ANDAMENTO')throw new ConflictException('Somente protocolo ativo e em andamento pode ser editado.');let procedureName: string|null|undefined; if(dto.procedureId){const p=await this.procedures.getById(dto.procedureId);procedureName=p.name;}return this.protocols.update(id,{procedureId:dto.procedureId,procedureName,date:dto.date?new Date(dto.date):undefined,title:dto.title?.trim(),chiefComplaint:text(dto.chiefComplaint),evaluation:text(dto.evaluation),objective:text(dto.objective),proposedProtocol:text(dto.proposedProtocol),guidelines:text(dto.guidelines),notes:text(dto.notes)});}
 async changeStatus(id:string,status:ProtocolStatus){const current=await this.require(id);const allowed:Record<ProtocolStatus,ProtocolStatus[]>={EM_ANDAMENTO:['CONCLUIDO','CANCELADO'],CONCLUIDO:[],CANCELADO:[]};if(!allowed[current.status].includes(status))throw new ConflictException('Transição de status não permitida.');return this.protocols.update(id,{status});}
 async inactivate(id:string){const p=await this.require(id);if(!p.active)throw new ConflictException('Protocolo já está inativo.');return this.protocols.update(id,{active:false,deletedAt:new Date()});}
 async reactivate(id:string){const p=await this.require(id);if(p.active)throw new ConflictException('Protocolo já está ativo.');return this.protocols.update(id,{active:true,deletedAt:null});}
 async addSession(id:string,dto:CreateProtocolSessionDto){const protocol=await this.require(id);if(!protocol.active||protocol.status!=='EM_ANDAMENTO')throw new ConflictException('Sessões só podem ser acrescentadas a protocolo ativo e em andamento.');let appointmentSnapshot:string|null=null;if(dto.appointmentId){const appointment=await this.appointments.getById(dto.appointmentId);if(appointment.clientId!==protocol.clientId)throw new BadRequestException('Atendimento pertence a outro cliente.');if(appointment.status!=='REALIZADO')throw new BadRequestException('Somente atendimento realizado pode ser vinculado.');if(await this.protocols.findSessionByAppointmentId(dto.appointmentId))throw new ConflictException('Atendimento já vinculado a uma sessão de protocolo.');appointmentSnapshot=appointment.procedureName||'Atendimento realizado';}let procedureName:string|null=null;if(dto.procedureId){procedureName=(await this.procedures.getById(dto.procedureId)).name;}return this.protocols.createSession({protocolId:id,date:new Date(dto.date),procedureId:dto.procedureId,procedureName,appointmentId:dto.appointmentId,appointmentSnapshot,procedurePerformed:dto.procedurePerformed.trim(),professional:text(dto.professional),productsUsed:text(dto.productsUsed),parameters:text(dto.parameters),evolution:text(dto.evolution),guidelines:text(dto.guidelines),notes:text(dto.notes)});}
 private async require(id:string){const p=await this.protocols.findById(id);if(!p)throw new NotFoundException('Protocolo não encontrado.');return p;}
}
